### ISSUE TITLE
Can't add new plugins by adding a line to .EverVim.vimrc

### ISSUE THREAD

**Issue by tuberry** [LER0ever/EverVim#20]
When I add a new plugin in the way mentioned in wiki, but it show me that 
`E492: Not an editor command: Plug 'JuliaEditorSupport/julia-vim'
`
Finally I make it by echoing the line to ~/.EverVim.bundles. What's wrong with it?

**Comment by LER0ever** [comment]
You can add custom plugins by adding a line to **`~/.EverVim.bundles`** instead of `.EverVim.vimrc`.  

It is because .EverVim.vimrc is sourced before Vim-Plug is initiated (to allow configurations for plugins).

I'll update the documentation soon. And adding plugins in .EverVim.vimrc will be supported in the future.

**Comment by Titubery** [comment]
@LER0ever  早知道用中文啦
