### ISSUE TITLE
Undefined variable: g:evervim_color_theme

### ISSUE THREAD

**Issue by JimmyJames707** [LER0ever/EverVim#29]
Hi,
 I am getting the same issue as here on Win 7 with neoVim:
https://github.com/LER0ever/EverVim/issues/24

However the error reported is given by Vim:

> PS ~\.evervim> nvim
> Error detected while processing ~\.EverVim\core\vimui.vim:
> line 21:
> E121: Undefined variable: g:evervim_color_theme
> E15: Invalid expression: 'color ' . g:evervim_color_theme
> Press ENTER or type command to continue
> 

While neoVim gives this error and will not start. I do not know how to get neoVim to start when it has an error.
> Neovim is taking too long to respond.

Also I was not able to set up Ctags because the link in your instructions is dead:
https://github.com/LER0ever/EverVim/wiki/Installation-on-Windows

> (Optional) Ctags
> 
> If you need tagbar support, you'll need to install ctags for Windows from here (click to download)

Edit: Ignore my comment on Ctags, the download is working again.

**Comment by JimmyJames707** [comment]
NeoVim started after I did :PlugInstall in Vim. So it appears you need to install EverVim on Vim before NeoVim can use it.

Also another issue, when NeoVim started the first time and after restarting Windows, it warns that the Knack NF font has a bad pitch. 

> Warning: Font "Knack NF" reports bad fixed pitch metrics.

The fonts are missing the right edges in neoVim, but in Vim the font looks fine.

**Comment by LER0ever** [comment]
Hi @JimmyJames707 , undefined variables about color themes only occurs when you first boot up EverVim, because at that point the color theme packages have not yet been installed. And you can just hit Enter to skip that and the plugin installation should automatically begin. But from your description, I assume **you did hit enter, but nothing happened, and you did try run :PlugInstall immediately after, but it still doesn't work**. (Right?)

I currently don't have a Windows 7 installed, but I can try a fresh installation on my WIndows 10 environment.

As for ctags download link... The ctags project is hosted on SourceForge, which is under heavy DDoS attack in the past few days, many projects relying on their file storage service (e.g. Manjaro, MinGW, and Ctags) may encounter problems with downloading from SF. 

You can just install EverVim without ctags for now. And just press 'u' on the startup screen to trigger a full upgrade **after ctags is in your PATH**, and tagbar feature should be automatically re-enabled.:)

**Comment by LER0ever** [comment]
Bug confirmed and reproducable on Windows platform. I've fixed the undefined variable, but it seems that the cause is something else. Neovim-win32 at that time is not even responding to keyboard Enter. I'll probably try a git snapshot of Neovim later (after I finished my midterms). 

Right now, the problem seems undeterministic, I tried removing all the `if NVIM()` code and run just like what Vim would see, but it still won't pass that and refuse to start plugin installation. It may be because of some changes from neovim 0.2 to 0.2.x.

**Comment by LER0ever** [comment]
Hi @JimmyJames707 , this bug is caused by Neovim 0.2's incorrect handling of Windows terminal environment, and therefore echo message cannot be skipped using keyboard event. I've temporarily made an work around, which is simply disable output on the initial installation. **Everything should work fine now.**

For future problematic installation under Windows, there is now a Appveyor autobuild set up for downloading and precompiling the plugins for Windows. Therefore, if you don't want to spend time cloning and installing the plugin on your local machine, you can just download the bundle zip and unzip it to the .EverVim folder.

Link to the latest Windows bundle artifact is [here](https://ci.appveyor.com/api/projects/LER0ever/EverVim/artifacts/EverVim-bundle-win32.zip).
