### ISSUE TITLE
I have little problem in chinese(中文乱码)

### ISSUE THREAD

**Issue by sparksofire** [LER0ever/EverVim#3]
![screenshot 2017-04-22 at 02 20 00](https://cloud.githubusercontent.com/assets/21191415/25291009/eea0ae68-2695-11e7-9ff6-5faf1043deee.png)

**Comment by sparksofire** [comment]
Is the problem of neovim or EverVim?

**Comment by LER0ever** [comment]
Hi, it's because you haven't installed the font as described in the installation instruction. You'll need to install Knack Nerd Font Mono and set the terminal font to that as well. After that, the font in the status line should display properly.
Let me know if you still have issues with lightline characters.

**Comment by sparksofire** [comment]
Ok!Thanks!

**Comment by LER0ever** [comment]
Closed as resolved. Feel free to reopen.
