### ISSUE TITLE
Missing in doc

### ISSUE THREAD

**Issue by ksideks** [LER0ever/EverVim#30]
Hi,
I tried to install custom plugin and without `let g:override_evervim_bundles = 1` in `.EverVim.vimrc` did not work. I think that this info should be in the wiki.

**Comment by LER0ever** [comment]
Hi @ksideks , sorry for the incomplete documentation, the custom bundle feature was added pretty recently, and I haven't got time to update the doc.

But it will soon be in the new "Getting Started" wiki page, where I would put explanations of most "initial configuration" options to help user actually get started, instead of wasting time figuring out undocumented problems on their own. :(
