### ISSUE TITLE
EverVim: Duplicate session, opening read-only...

### ISSUE THREAD

**Issue by skjorrface** [LER0ever/EverVim#31]
This is not quite an issue but a question, as I'm not finding a solution anywhere else. As described in title, when trying to open certain files I get that message and I'm unable to edit the files mentioned above. I tried using commands available from session.vim or xolox/vim-sessions but I always get: "Not an editor command". How can I solve this problem? Thanks and sorry if this is not the right place to ask a question.

**Comment by LER0ever** [comment]
Hi @skjorrface , this happens when you open the same file in two Vim instance. If this is the case, you can usually solve this by closing both Vim instance and reopen the file. 
But if it's because your Vim had been killed accidentally, you can try remove the `~/.vimswap` folder in your home directory and everything should work fine.

**Comment by skjorrface** [comment]
Thank you very much, this happened even over different reboots, removing ~/.vimswap worked!
