### ISSUE TITLE
Shortcuts for tabs are not valid?

### ISSUE THREAD

**Issue by yydxwz** [LER0ever/EverVim#36]
H  Move to previous tab
L  Move to next tab
I can not change  tabs~~~

**Comment by LER0ever** [comment]
Hi @fxbszj , I currently cannot reproduce this under either Windows or Linux.
Just so you know, tab is not the same as buffers, in order to switch between tabs, you'll first need to create multiple tabs. 
If you want to create tabs, you can press `<Leader>et` and enter the filename you want to edit in a new tab.
If you just want to switch between buffers, `<Leader>bs` gives you a list of buffers currently open for you to choose.

If you are still having trouble switching tabs, please also attach a screenshot of your running vim, as well as the OS info & Vim version.

**Comment by yydxwz** [comment]
@LER0ever  Thank you! And maybe you can write that in wiki.
