### ISSUE TITLE
Manipulating Colorscheme

### ISSUE THREAD

**Issue by Xiaoming94** [LER0ever/EverVim#40]
Hello. Is there an option in EverVim that let's you manipulate the current colorscheme?

For doing something like instance options like `hi Normal ctermbg=none` in Evervim

**Comment by LER0ever** [comment]
Hi, if you need to change a specific highlighting group, adding that line to `.EverVim.vimrc` should work.
You can also change the colorscheme using `let g:evervim_color_theme="xxx"`, or using `<leader>.r` (leader dot r) to select from a list of themes.

**Comment by Xiaoming94** [comment]
Tried out different similar config, Looks like it doesn't.

This time though I tried out `au BufNewFile, BufRead   *.mod   set syntax=ampl` and it looks like this had no effect on the editor

It kind of looks like if it's not a `let g:*evervim*` like config command, the command has no effect if put in `.EverVim.vimrc`

**Comment by LER0ever** [comment]
@Xiaoming94 sorry if I misunderstood your need, if you only want the effects of `hi Normal ctermbg=none` , there is a bunch of transparency plugins out there, just grab one and it should work. In fact, I did include one in this commit [aa6a33](https://github.com/LER0ever/EverVim/commit/70ec23155cdcfc30eaf72240d13b4e57e2aa6a33), but deleted later.

But if you want some advanced highlighting group operations, you should fork the existing colorscheme, and include it as an additional plugin, instead of hacking the colors in EverVim.

**Comment by Xiaoming94** [comment]
@LER0ever Thanks for the answer. My last comment was about the fact that regular `.vimrc` config options are ignored when putting them into `~/.EverVim.vimrc`.

But maybe it's should be posted as a separate issue?

**Comment by LER0ever** [comment]
@Xiaoming94 I just tested the autocmds in EverVim.vimrc, it seems to me that these au's works perfectly.
![2018-05-23-160634_2560x1440_scrot](https://user-images.githubusercontent.com/10568668/40411576-73459fca-5ea3-11e8-8849-c2e72a9b12d0.png)

And if you still have issues, but not related to the current one, please don't hesitate to open a new issue.

**Comment by Xiaoming94** [comment]
Looks like my stuff didn't work because there were already filetypes defined for those file I was trying to use autocmd on. My bad, thank you for your help.

I might have a question though regarding NERDTree in this pluggin, but that I will post as a separate issue. Closing this now, Thanks for all the help and hard work!
