### ISSUE TITLE
Unable to update components

### ISSUE THREAD

**Issue by duytrung** [LER0ever/EverVim#43]
Hi,

I have the following error when trying to update the plugins. Please show me how to fix these errors:
![image](https://user-images.githubusercontent.com/2046672/42162345-804cea02-7e3d-11e8-885f-411d30731a2c.png)

Thanks

**Comment by LER0ever** [comment]
Hi @duytrung , I just tried updating from a previous version on Windows and it works at least for me.
![image](https://user-images.githubusercontent.com/10568668/42180725-e860ccf2-7dfd-11e8-87c4-d4486d28778e.png)

**Could you please press `<zR>` (these two keys) on the error screen to unfold the error, otherwise I cannot see the git error message.**

And I've closed the other similar issue also opened by yourself.

**Comment by duytrung** [comment]
Yay! 
Here it is:
![image](https://user-images.githubusercontent.com/2046672/42447580-805a70d8-83b9-11e8-9cf7-c1dee37b66e0.png)

**Comment by LER0ever** [comment]
@duytrung then obviously you should try
- `:PlugClean`
- then press u at startup screen

But the wierd thing is that I remember putting plugclean process in the upgrade...
