### ISSUE TITLE
Knack Nerd Font no longer exists

### ISSUE THREAD

**Issue by sez11a** [LER0ever/EverVim#48]
Hi, 

I just installed EverVim yesterday, and I wanted to let you know that the Knack Nerd Font isn't in the Nerd Fonts repo anymore. You may want to choose a different default font.

**Comment by LER0ever** [comment]
Hi @sez11a , it's true that Nerd Fonts renamed their Knack Nerd Font to Hack Nerd Font. But the link I put in the [wiki](https://github.com/LER0ever/EverVim/wiki) points to the 1.2 release which was released last year and still includes Knack Nerd Fonts. If you used that link in the wiki, you've probably got Knack Nerd Font installed already, it not, please use that link instead of master branch.

_I do plan to use the latest 2.0 version of Nerd Fonts (specifically Hack Nerd Font) in the next breaking change, which should be coming up in late november, and should break all of the previous installations of EverVim... For now, I'm still working on the big update, so the master branch of EverVim is not updated that frequently_

I'll close this for now since the upstream change does not affect the normal installation. Feel free to reopen or comment should you have further questions/issues.
