### ISSUE TITLE
can support python2

### ISSUE THREAD

**Issue by yangsui9999** [LER0ever/EverVim#7]
thanks for you work, for some reasons I can only use python2, if EverVim can use python2 will be very nice.

**Comment by LER0ever** [comment]
Hi, the only thing that needs python on Linux & macOS is YouCompleteMe and it supports both python2 and python 3. So if only python 2 is available to you, please make sure you have python2 and pip2 installed, and the installation should work just fine since YouCompleteMe will automatically switch to python 2 interpreter (just tested on ubuntu 16.04).
